#!/bin/bash
# ChkAcc - Snoops through auth.log files to see who has logged in and who has failed trying
# For best results, set $RepeatedMsgReduction off in /etc/rsyslog.conf
# Geolocation database needed for -g option
#  apt install geoip-bin geoip-database
#
# Arguments
#  -f - Check for failed logon attempts
#  -s - Check for successful logons
#  -g - Use geolocation database to identify source
#  -e - Email output to admin
#  -a - Enable all options

VER="1.00"

usage()
{
   echo "chkacc ${VER} - Check auth.log for successful and failed remote logon attempts"
   echo " -f - Check for failed logon attempts"
   echo " -s - Check for successful logons"
   echo " -g - Use geolocation database to identify source"
   echo " -e - Email output to admin"
   echo " -a - Enable all options"
   echo " -h - Display this text"
   echo
}

chklocal()
{
   local o=""
   local c=$(grep $1 /etc/hosts | cut -f2)
   if [ ${1:0:8} = "192.168." ] ; then
      if [ -z "$c" ] ; then
         o="Local address"
      else
         o=$c
      fi
   elif [ ${1:0:4} = "172." ] ; then
      if [ ${1:4:2} -ge 16 ] && [ ${1:4:2} -le 31 ] ; then
         o="Local address"
      else
         o=$(geoiplookup $1 | sed 's/GeoIP Country Edition://' 2> /dev/null)
      fi
   elif [ ${1:0:3} = "10." ] ; then
      o="Local address"
   else
      o=$(geoiplookup $1 | sed 's/GeoIP Country Edition://' 2> /dev/null)
   fi
   echo " "$o
}

TOEMAIL="you@mail.com"
FREMAIL="server@email.net"
# Change to how you want to identify your server
SERVERNAME=$HOSTNAME

FAIL=0
SUCC=0
GEO=0
EMAIL=0

if [[ ! -d "/etc/chkacc" ]]; then
   sudo mkdir /etc/chkacc
   sudo chmod 777 /etc/chkacc
   echo "s/for invalid user  from/for \[BLANK\] from/" > /etc/chkacc/filter.sed
   echo "s/for invalid user/for/" >> /etc/chkacc/filter.sed
fi

if [ $# = 0 ]
then
   usage
   exit 0
fi

while getopts ":fsgeah" opt; do
   case ${opt} in
      f ) FAIL=1 ;;
      s ) SUCC=1 ;;
      g ) GEO=1 ;;
      e ) EMAIL=1 ;;
      a ) FAIL=1; SUCC=1; GEO=1; EMAIL=1 ;;
      h ) usage ;;
      * ) echo "Usage: chkacc [-fsgeah] - Invalid argument:" $OPTARG 1>&2 ;;
   esac
done

if [ $FAIL = 1 ]; then
   zgrep -h "Failed password" /var/log/auth.log.4.gz /var/log/auth.log.3.gz /var/log/auth.log.2.gz \
     /var/log/auth.log.1 /var/log/auth.log 2> /dev/null | sed -f /etc/chkacc/filter.sed | tr -s ' ' | \
     cut -f1,2,3,9,11 -d ' ' > /etc/chkacc/failed.txt
   echo "Failed attempts by account" > /etc/chkacc/outfile
   cut -f4 -d ' ' /etc/chkacc/failed.txt | sort | uniq -c | sort -nr >> /etc/chkacc/outfile
   echo >> /etc/chkacc/outfile

   if [ $GEO = 1 ]; then
      echo "Failed attempts by geolocation" >> /etc/chkacc/outfile
      cut -f5 -d ' ' /etc/chkacc/failed.txt | sort | uniq | \
      (
         while read x; do
            echo -n $x "-";
            chklocal $x
         done
      ) >> /etc/chkacc/outfile
      echo >> /etc/chkacc/outfile
   fi
fi

if [ $SUCC = 1 ]; then
   zgrep -h " Accepted" /var/log/auth.log.4.gz /var/log/auth.log.3.gz /var/log/auth.log.2.gz \
     /var/log/auth.log.1 /var/log/auth.log 2> /dev/null | tr -s ' ' | cut -f1,2,3,9,11 -d ' ' > /etc/chkacc/success.txt
   echo "Successful logins" >> /etc/chkacc/outfile
   cut -f5 -d ' ' /etc/chkacc/success.txt | sort | uniq -c | sort -nr >> /etc/chkacc/outfile
 
   if [ $GEO = 1 ]; then
      echo >> /etc/chkacc/outfile
      echo "Successful logins by geolocation" >> /etc/chkacc/outfile
      cat /etc/chkacc/success.txt | cut -f5 -d ' ' | sort | uniq | \
      (
         while read x; do
            echo -n $x "-";
            chklocal $x
         done
      ) >> /etc/chkacc/outfile
   fi
fi

if [ -f /etc/chkacc/outfile ]; then
   if [ $EMAIL = 1 ]; then
      cat /etc/chkacc/outfile | mail -s "chkacc report: ${SERVERNAME}" -a "From: ${FREMAIL}" $TOEMAIL
   else
      cat /etc/chkacc/outfile
   fi
   rm /etc/chkacc/outfile
fi
